// Generate supabase/seed.sql from scripts/seed-data.mjs.
//
//   node scripts/generate-sql.mjs
//
// The emitted SQL is idempotent (ON CONFLICT upserts) and can be pasted into
// the Supabase SQL editor. It relies on the unique constraints created in
// supabase/schema.sql.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { tracks } from "./seed-data.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../supabase/seed.sql");

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const json = (obj) => `${q(JSON.stringify(obj))}::jsonb`;

const lines = [
  "-- SFMA seed data — generated by scripts/generate-sql.mjs. Do not edit by hand.",
  "-- Run supabase/schema.sql first (creates tables + unique constraints).",
  "begin;",
  "",
];

for (const t of tracks) {
  lines.push(`-- ============ Track: ${t.title} ============`);
  lines.push(
    `insert into tracks (title, slug, description, order_index)`,
    `values (${q(t.title)}, ${q(t.slug)}, ${q(t.description)}, ${t.order_index})`,
    `on conflict (slug) do update set`,
    `  title = excluded.title, description = excluded.description, order_index = excluded.order_index;`,
    "",
  );

  for (const m of t.modules) {
    const trackRef = `(select id from tracks where slug = ${q(t.slug)})`;
    lines.push(
      `insert into modules (track_id, title, slug, description, order_index)`,
      `values (${trackRef}, ${q(m.title)}, ${q(m.slug)}, ${q(m.description)}, ${m.order_index})`,
      `on conflict (track_id, slug) do update set`,
      `  title = excluded.title, description = excluded.description, order_index = excluded.order_index;`,
      "",
    );

    for (const l of m.lessons) {
      const content = [
        { type: "meta", author: l.author, frequency: l.frequency },
        ...l.blocks,
      ];
      const moduleRef =
        `(select id from modules where slug = ${q(m.slug)} ` +
        `and track_id = (select id from tracks where slug = ${q(t.slug)}))`;
      lines.push(
        `insert into lessons (module_id, title, slug, content, order_index)`,
        `values (${moduleRef}, ${q(l.title)}, ${q(l.slug)}, ${json(content)}, ${l.order_index})`,
        `on conflict (module_id, slug) do update set`,
        `  title = excluded.title, content = excluded.content, order_index = excluded.order_index;`,
        "",
      );
    }
  }
}

lines.push("commit;", "");

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out}`);
